name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: pip install -r requirements.txt pyinstaller

    - name: Build exe
      run: pyinstaller --onefile app.py

    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: shop-manager-exe
        path: dist/app.exe
